---
title: "plot_pcair.Rmd"
author: "Isabelle"
date: "2025-01-15"
output: html_document
---

```{r}
library(data.table)
library(dplyr)
library(knitr)
library(ggplot2)
library(wesanderson)
#Darjeeling2 = c("#ECCBAE", "#046C9A", "#D69C4E", "#ABDDDE", "#000000")

ghlist<-fread('GH_idlist.txt')
jalist<-fread('JA_idlist.txt')
salist<-fread('SA_idlist.txt')
uslist<-fread('US_idlist.txt')

pcair<-fread('METS735_rsid_snpfiltered_PCAIR.txt',header=T)
```

```{r}
ghlist<-ghlist%>%mutate(country='GH')
jalist<-jalist%>%mutate(country='JA')
salist<-salist%>%mutate(country='SA')
uslist<-uslist%>%mutate(country='US')
poplist<-rbind(ghlist,jalist)%>%rbind(salist)%>%rbind(uslist)

pcairpops<-inner_join(pcair,poplist,by=c('id'='IID'))
```

```{r}
cols<-c("id","PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10","PC11","PC12","PC13","PC14","PC15","PC16","PC17","PC18","PC19","PC20","PC21","PC22","PC23","PC24","PC25","PC26","PC27","PC28","PC29","PC30","PC31","PC32","related","FID","SEX","country")
colnames(pcairpops)<-cols

fwrite(pcairpops,'METS735_rsid_snpfiltered_PCAIR_wpops.txt')
```

```{r}
pop=factor(pcairpops$country,levels=c('GH','US','SA','JA'))
#table(pcairpops$country)
rel=factor(pcairpops$related,levels=c('yes','no'))

ggplot(pcairpops,aes(x=PC1,y=PC2,color=pop)) + geom_point(aes(shape=factor(pcairpops$related)),size=2) + theme_bw(16) + scale_color_manual(values=wes_palette('Darjeeling2',4,type='discrete'))+labs(title='METS genotype PCs',color='METS\npopulation',shape='related individuals') +scale_shape_manual(values=c(20,3))

ggplot(pcairpops,aes(x=PC1,y=PC2,color=rel)) + geom_point(aes(shape=factor(pcairpops$related)),size=1) + theme_bw(16) +labs(title='METS genotype PCs',color='related\nindividuals',shape='related\nindividuals')+scale_shape_manual(values=c(20,3))

#geom_point(aes(shape=factor(pcairpops$related)),size=1) +scale_shape_manual(values=c(3,20))
```

```{r}
pops = fread("/home/wheelerlab3/Data/1000g_phase3_hg38_plink/all_hg38.psam")
evec = fread("/home/isabelle/METS/updatedQC/METS_1kg_PCA10.eigenvec")
eval = fread("/home/isabelle/METS/updatedQC/METS_1kg_PCA10.eigenval")

#merge pops
all = left_join(evec,pops,join_by(IID==`#IID`))
kgenomes<-filter(all,!is.na(SuperPop))
all2 = full_join(kgenomes,pcairpops)
all3 = mutate(all2,pop=ifelse(is.na(country),SuperPop,country),
             finepop=ifelse(is.na(country),Population,country))

for(i in 1:nrow(all3)){
  if(is.na(all3[i,17])){all3[i,16]<-'METS'}
}

#removing relatedness shapes for this one, not enough wes colors for all THIRTY pops phew what
ggplot(all3,aes(x=PC1,y=PC2,color=finepop)) + geom_point(size=1,aes(shape=SuperPop)) + theme_bw(12) +labs(title='METS genotype PCs with 1KGenomes reference populations',color='Population',shape='SuperPop')


```

